---
about:
  template: marquee
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/vahram-p/
    - icon: github
      text: GitHub
      href: https://www.github.com/vahram-pg
page-layout: full
sidebar: false
toc: false
---

**About This Site** 

Hi, I’m Vahram! 

Welcome to my [digital garden](https://maggieappleton.com/garden-history?ref=ideasurg.pub) — a collection of my notes and ideas shared on the internet.

This journey began in early 2021, inspired by some college notes I had compiled using Jupyter Notebooks and various online resources I explored during my free time. Recently, I’ve been experimenting with static page generators (like [Quarto](https://github.com/quarto-dev)) to transform my notes into a format that’s both functional and visually appealing for the web.  

I strive to clearly distinguish between original work and borrowed content, always providing proper citations where applicable. For more details on content usage and attribution, please refer to the **Copyright** section.  

---  

**License** 

**Copyright (c) 2023 Vahram Poghosyan**  

The materials on this site — including the styling, custom images, videos, code, and most written content — are protected under copyright law, unless explicitly stated otherwise (e.g., content attributed to others or in the public domain).  

If you'd like to reuse any assets or content, feel free to reach out to me at **vapogyan@gmail.com** with your request. Exceptions will be readily granted for reasonable use!  